export const CartActionTypes = {
  TOGGLE_CART_SHOWN: "TOGGLE_CART_SHOWN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  REDUCE_QUANTITY: "REDUCE_QUANTITY",

  //SAGAS
  CLEAR_CART: "CLEAR_CART",
  CLEAR_CART_SUCCESS: "CLEAR_CART_SUCCESS",
  CLEAR_CART_FAIL: "CLEAR_CART_FAIL"
};

export default CartActionTypes;
