const shopActionTypes = {
  COLLECTIONS_FETCH: "FETCH_COLLECTIONS",
  COLLECTIONS_DID_FETCH: "COLLECTIONS_DID_FETCH",
  COLLECTIONS_FETCH_FAIL: "COLLECTIONS_FETCH_FAIL"
};

export default shopActionTypes;
