const userActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_SIGN_IN: "GOOGLE_SIGN_IN",
  GOOGLE_SIGN_IN_SUCCESS: "GOOGLE_SIGN_IN_SUCCESS",
  GOOGLE_SIGN_IN_FAIL: "GOOGLE_SIGN_IN_FAIL",
  EMAIL_SIGN_IN: "EMAIL_SIGN_IN",
  EMAIL_SIGN_IN_SUCCESS: "EMAIL_SIGN_IN_SUCCESS",
  EMAIL_SIGN_IN_FAIL: "EMAIL_SIGN_IN_FAIL"
};

export default userActionTypes;
